FROM ubuntu:16.04

WORKDIR /root

RUN apt-get update \
 && apt-get -y upgrade \
 && apt-get -y install git wget vim iproute2 strace build-essential sqlite openssl \
                       xz-utils libgit2-dev graphviz libbz2-dev apt-utils curl \
                       libreadline-dev libssl-dev libsqlite3-dev libffi-dev \
                       procps autoconf automake libncurses5-dev \
 && apt-get clean \
 && rm -rf /var/cache/apt

WORKDIR /root

ENV GIT_SRC_VERSION=v2.37.0
RUN git clone --single-branch --depth 1 -b "$GIT_SRC_VERSION" https://github.com/git/git.git \
 && cd git \
 && make configure \
 && ./configure --prefix=/usr/local --with-tcltk=no --with-expat=no --with-python=no \
 && echo "NO_TCLTK=YesPlease" >> config.mak.autogen \
 && echo "NO_PERL=YesPlease" >> config.mak.autogen \
 && sed -i '0,/^NO_GETTEXT/s/^NO_GETTEXT.*/NO_GETTEXT=YesPlease/' config.mak.autogen \
 && make \
 && make install \
 && rm -rf /root/git

ENV PYENV_ROOT=/usr/local/pyenv
ENV PATH=$PYENV_ROOT/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
ENV PYENV_INSTALLER_URL=https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer

RUN umask 0022 ; curl -sSL "$PYENV_INSTALLER_URL" | bash

ARG PY_INSTALL="3.9.9"
ARG PY_V=3.9.9

ENV CONFIGURE_OPTS="--enable-shared"

RUN umask 0022 \
  ; eval "$(pyenv init --path)" \
  ; set -e \
  ; for py_v in $PY_INSTALL; do pyenv install $py_v; rm -rf /tmp/python-build*; done \
  ; pyenv global $PY_V \
  ; echo $PY_V > /etc/PY_V; chmod 0644 /etc/PY_V

RUN find /usr/local/pyenv -type f -name libpython\*.so | xargs -rn1 dirname | sort -hu | tee /etc/ld.so.conf.d/pyenv.conf \
  ; chmod 0644 /etc/ld.so.conf.d/pyenv.conf \
  ; ldconfig -v

COPY misc/kersplat.sh /etc/profile.d/kersplat.sh
COPY misc/bashrc /root/.bashrc
COPY misc/bashrc /work/.bashrc
COPY misc/docker-entrypoint.sh /

RUN chown -cR root:root /root \
  ; chmod 0755 /docker-entrypoint.sh \
  ; chmod 0644 /etc/profile.d/kersplat.sh \
  ; chmod -cR o=g /usr/local/pyenv

WORKDIR /work
ENV HOME=/work LC_ALL=C.UTF-8

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "bash", "-o", "vi" ]
